name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7'
          bundler-cache: true

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Validate Dockerfile (build)
        run: |
          docker --version || true
          docker build --file Dockerfile --tag hotwired-november-todoapp:ci .

      - name: Run RuboCop
        run: bundle exec rubocop --parallel --format simple

      - name: Run strong_versions
        run: |
          gem install strong_versions
          strong_versions

      - name: Prepare DB
        run: |
          bin/rails db:create db:migrate db:schema:dump

      - name: Run RSpec
        run: bundle exec rspec --format documentation
